---
title: "#django で URL をバリデーションする例"
emoji: "🖥"
type: "tech"
topics: ["Django"]
published: true
---

```
from django.core.validators import URLValidator

URLValidator()('WAAAAAAA!')
```

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/django/core/validators.py", line 114, in __call__
    raise ValidationError(self.message, code=self.code)
django.core.exceptions.ValidationError: ['有効なURLを入力してください。']
```

# Original by Github issue

https://github.com/YumaInaura/YumaInaura/issues/1790








<!-- Update From Qiita API -->

# チャットメンバー募集


何か質問、悩み事、相談などあればLINEオープンチャットもご利用ください。

https://line.me/ti/g2/eEPltQ6Tzh3pYAZV8JXKZqc7PJ6L0rpm573dcQ





# Twitter


https://twitter.com/YumaInaura


<!-- Update From Qiita API -->


