---
title: "#python で 例外 ( runtime error ) を発生させる  raise RuntimeError('message')"
emoji: "🖥"
type: "tech"
topics: ["Python"]
published: true
---

```
>>> raise RuntimeError('oops!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: oops!
```

# Original by Github issue

https://github.com/YumaInaura/YumaInaura/issues/2012








<!-- Update From Qiita API -->

# チャットメンバー募集


何か質問、悩み事、相談などあればLINEオープンチャットもご利用ください。

https://line.me/ti/g2/eEPltQ6Tzh3pYAZV8JXKZqc7PJ6L0rpm573dcQ





# Twitter


https://twitter.com/YumaInaura


<!-- Update From Qiita API -->


